name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate version
        run: |
          VERSION=$(cat VERSION)
          TAG=${GITHUB_REF#refs/tags/v}
          if [ "$VERSION" != "$TAG" ]; then
            echo "Version mismatch: VERSION=$VERSION, TAG=$TAG"
            exit 1
          fi

      - name: Create release asset
        run: |
          cd custom_components
          zip -r ../mashov.zip mashov/
          cd ..

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./mashov.zip
          asset_name: mashov.zip
          asset_content_type: application/zip

      - name: Notify HACS
        run: |
          echo "Release published. HACS will automatically detect the new version."

